---
version: 2
project_name: puppet-agent-exporter
env:
  - KO_DOCKER_REPO={{ if index .Env "KO_DOCKER_REPO"  }}{{ .Env.KO_DOCKER_REPO }}{{ else }}ghcr.io/retailnext/puppet-agent-exporter{{ end }}
gomod:
  proxy: true
before:
  hooks:
    - go mod tidy
builds:
  - id: puppet-agent-exporter-build
    binary: puppet-agent-exporter
    env:
      - CGO_ENABLED=0
    flags:
      - -trimpath
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
kos:
  - id: puppet-agent-exporter-ko
    build: puppet-agent-exporter-build
    base_import_paths: true
    platforms:
      - linux/amd64
      - linux/arm64
    tags:
      - "v{{.Version}}"
      - "{{if not .Prerelease}}{{if not .IsSnapshot}}{{if not .IsNightly}}latest{{end}}{{end}}{{end}}"
      - "{{if not .Prerelease}}{{if not .IsSnapshot}}{{if not .IsNightly}}v{{.Major}}{{end}}{{end}}{{end}}"
      - "{{if not .Prerelease}}{{if not .IsSnapshot}}{{if not .IsNightly}}v{{.Major}}.{{.Minor}}{{end}}{{end}}{{end}}"
nfpms:
  - id: puppet-agent-exporter-nfpm
    package_name: puppet-agent-exporter
    formats:
      - deb
    license: Apache 2.0
    homepage: https://github.com/retailnext/puppet-agent-exporter
    maintainer: Erik Swanson <erik@retailnext.net>
    description: Prometheus Exporter for Puppet Agent
checksum:
  name_template: 'checksums.txt'
changelog:
  sort: asc
  filters:
    exclude:
      - '^chore\(ci\):'
      - '^chore\(deps\):'
      - '^docs:'
      - '^test:'
